//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAPIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int deptId { get; set; }
        public string DeptName { get; set; }
        public int managerId { get; set; }
        public bool isActive { get; set; }
    }
}
