//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAPIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Menu
    {
        public int menuId { get; set; }
        public string menuTitleAr { get; set; }
        public string menuTitleEn { get; set; }
        public string menuPah { get; set; }
        public Nullable<int> menuParentId { get; set; }
        public string menuIcon { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public string Images { get; set; }
        public string Description { get; set; }
        public string color { get; set; }
        public string path { get; set; }
    }
}
