//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAPIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Users
    {
        public string UserName { get; set; }
        public string password { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> roleId { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Department { get; set; }
        public string image { get; set; }
        public long userId { get; set; }
    }
}
