//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAPIProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Role
    {
        public int roleId { get; set; }
        public string roleName { get; set; }
        public bool IsActive { get; set; }
    }
}
